import { createContext, useContext, useState, useEffect } from 'react';

const T = {
  ar: {
    currency: '₪',
    storeName: 'هانوك سناكس',
    storeSubtitle: 'Korean Snacks Store',
    navStore: 'المتجر',
    navAdmin: 'الإدارة',
    langToggle: 'EN',

    heroTitle: 'وجبات كورية أصيلة في بيتك',
    heroSubtitle: 'اكتشف أشهى التشكيلات الكورية — رامن، رقائق، حلوى، مشروبات وأكثر',
    heroShopNow: 'تسوق الآن',
    heroBrowse: 'تصفح المتجر',
    heroStatProducts: 'منتج',
    heroStatCategories: 'فئات',
    heroStatAuthentic: 'أصيل',
    heroStatDelivery: 'توصيل سريع',
    feat1Title: 'شحن مجاني',
    feat1Desc: 'عند الطلب فوق 100 ₪',
    feat2Title: 'منتجات أصيلة',
    feat2Desc: 'مستوردة مباشرة من كوريا',
    feat3Title: 'توصيل سريع',
    feat3Desc: 'شحن سريع مضمون',
    feat4Title: 'دفع آمن',
    feat4Desc: 'الدفع عند الاستلام',
    mostBoughtTitle: 'الأكثر مبيعاً',
    mostBoughtSubtitle: 'المفضلة لدى عملائنا',
    viewAllProducts: 'تصفح جميع المنتجات',
    categoriesTitle: 'تصفح الفئات',
    catItems: 'منتج',

    catAll: 'الكل',
    catRamen: 'رامن',
    catChips: 'رقائق',
    catCandy: 'حلوى',
    catDrinks: 'مشروبات',
    catBiscuits: 'بسكويت',

    addToCart: '+ أضف للسلة',
    inCart: '✓ في السلة',
    outOfStock: 'غير متاح',
    badgeNew: 'جديد',
    badgeFeatured: '⭐ مميز',
    badgeOutOfStock: 'نفد المخزون',

    catalogHeroBadge: '🇰🇷 أفضل المنتجات الكورية الأصيلة',
    catalogHeroTitle: 'وجبات كورية في بيتك',
    catalogHeroSubtitle: '+ منتج أصيل يصلك على باب البيت',
    searchPlaceholder: 'ابحث عن منتج، علامة تجارية...',
    filterBtn: '⚙️ فلاتر',
    noResultsTitle: 'لا توجد منتجات مطابقة',
    noResultsDesc: 'جرب تغيير الفلاتر أو البحث بكلمات مختلفة',
    productsLabel: 'منتج',
    pageLabel: 'صفحة',
    ofLabel: 'من',
    sortFeatured: 'المميزة أولاً',
    sortPriceAsc: 'السعر: الأقل أولاً',
    sortPriceDesc: 'السعر: الأعلى أولاً',
    sortRating: 'الأعلى تقييماً',
    sortName: 'الاسم أبجدياً',
    maxPriceLabel: 'الحد الأقصى للسعر',
    minRatingLabel: 'الحد الأدنى للتقييم',
    inStockOnly: 'المتاح فقط',
    resetFilters: '↺ إعادة ضبط الفلاتر',

    cartTitle: '🛒 سلة المشتريات',
    emptyCartTitle: 'السلة فارغة',
    emptyCartMsg: 'لم تضف أي منتجات بعد. تصفح متجرنا واكتشف أشهى الوجبات الكورية!',
    browseStore: 'تصفح المتجر 🇰🇷',
    clearCart: '🗑️ إفراغ السلة',
    subtotal: 'المجموع الفرعي',
    shippingFee: 'رسوم الشحن',
    freeShippingLabel: 'مجاني 🎉',
    totalLabel: 'الإجمالي',
    checkoutBtn: 'إتمام الطلب ←',
    continueShoppingBtn: 'متابعة التسوق',
    orderSummaryTitle: 'ملخص الطلب',

    backToCartLink: '← العودة للسلة',
    checkoutTitle: 'إتمام الطلب',
    personalInfoTitle: '👤 المعلومات الشخصية',
    fullNameLabel: 'الاسم الكامل',
    namePlaceholder: 'مثال: أحمد محمد العمري',
    phoneLabel: 'رقم الجوال',
    phonePlaceholder: 'مثال: 0501234567',
    addressTitle: '📍 عنوان التوصيل',
    cityLabel: 'المدينة',
    cityPlaceholder: 'الرياض',
    districtLabel: 'الحي',
    districtPlaceholder: 'حي النزهة',
    streetLabel: 'اسم الشارع',
    streetPlaceholder: 'شارع الملك فهد',
    buildingLabel: 'رقم المبنى / الشقة',
    buildingPlaceholder: 'مبنى 12، شقة 3',
    notesLabel: 'ملاحظات إضافية',
    notesPlaceholder: 'أي تعليمات خاصة للتوصيل...',
    paymentTitle: '💳 طريقة الدفع',
    pmCod: 'الدفع عند الاستلام',
    pmCodDesc: 'ادفع نقداً عند وصول طلبك',
    pmCredit: 'بطاقة ائتمانية',
    pmCreditDesc: 'فيزا، ماستركارد، مدى',
    pmStc: 'STC Pay',
    pmStcDesc: 'الدفع عبر تطبيق STC Pay',
    confirmOrderBtn: '📲 أرسل الطلب عبر واتساب',
    secureInfo: 'معلوماتك محمية وآمنة',
    shippingLabel: 'الشحن',
    freeLabel: 'مجاني',
    nameRequired: 'الاسم مطلوب',
    phoneRequired: 'رقم الجوال مطلوب',
    phoneInvalid: 'رقم الجوال غير صحيح',
    cityRequired: 'المدينة مطلوبة',
    streetRequired: 'اسم الشارع مطلوب',
    formError: 'يرجى تصحيح الأخطاء في النموذج',
    orderSuccessTitle: 'تم استلام طلبك!',
    orderTotalLabel: 'إجمالي الطلب',
    shopAgainBtn: 'تسوق مجدداً 🛍️',

    storeLink: 'المتجر',
    productNotFound: 'المنتج غير موجود',
    backToStoreBtn: 'العودة للمتجر',
    quantityLabel: 'الكمية',
    unavailableBtn: 'غير متاح حالياً',
    viewCartBtn: 'عرض السلة',
    reviewsLabel: 'تقييم',
    specsTitle: 'مواصفات المنتج',
    specWeight: 'الوزن',
    specServings: 'الحصص',
    specOrigin: 'البلد',
    specBrand: 'العلامة التجارية',
    specCategory: 'الفئة',
    specHeat: 'مستوى الحرارة',
    specAvailability: 'التوفر',
    specAvailable: '✅ متاح',
    specOutOfStock: '❌ نفد المخزون',
    viewAllLink: 'عرض الكل',
    outOfStockBadge: 'نفد المخزون',
    heatLabels: ['', '🌶️ خفيف', '🌶️🌶️ معتدل', '🌶️🌶️🌶️ حار', '🌶️🌶️🌶️🌶️ حار جداً', '🌶️🌶️🌶️🌶️🌶️ ناري!'],
    galleryViews: {
      رامن: ['المنتج', 'طريقة التقديم', 'المكونات', 'العبوة'],
      رقائق: ['المنتج', 'في الوعاء', 'التوابل', 'العبوة'],
      حلوى: ['المنتج', 'التقديم', 'المكونات', 'العبوة'],
      مشروبات: ['المنتج', 'بارد', 'مع الثلج', 'العبوة'],
      بسكويت: ['المنتج', 'مع الشاي', 'مقطّع', 'العبوة'],
    },

    footerTagline: 'أفضل الوجبات الكورية الأصيلة في المملكة',
    footerContactTitle: 'تواصل معنا',
    footerEmail: 'info@hanooksnacks.com',
    footerPhone: '+966 50 000 0000',
    footerAddress: 'الرياض، المملكة العربية السعودية',
    footerHours: 'الأحد – الخميس: 9 ص – 9 م',
    footerLinksTitle: 'روابط سريعة',
    footerHome: 'الرئيسية',
    footerStore: 'المتجر',
    footerCart: 'السلة',
    footerRights: 'جميع الحقوق محفوظة',
  },

  en: {
    currency: '₪',
    storeName: 'Hanook Snacks',
    storeSubtitle: 'Korean Snacks Store',
    navStore: 'Store',
    navAdmin: 'Admin',
    langToggle: 'عربي',

    heroTitle: 'Authentic Korean Snacks, Delivered to Your Door',
    heroSubtitle: 'Discover the best Korean snacks — ramen, chips, candy, drinks and more',
    heroShopNow: 'Shop Now',
    heroBrowse: 'Browse Store',
    heroStatProducts: 'Products',
    heroStatCategories: 'Categories',
    heroStatAuthentic: 'Authentic',
    heroStatDelivery: 'Fast Delivery',
    feat1Title: 'Free Shipping',
    feat1Desc: 'On orders above ₪100',
    feat2Title: 'Authentic Products',
    feat2Desc: 'Imported directly from Korea',
    feat3Title: 'Fast Delivery',
    feat3Desc: 'Fast shipping guaranteed',
    feat4Title: 'Secure Payment',
    feat4Desc: 'Cash on delivery',
    mostBoughtTitle: 'Best Sellers',
    mostBoughtSubtitle: 'Customer Favorites',
    viewAllProducts: 'Browse All Products',
    categoriesTitle: 'Browse Categories',
    catItems: 'items',

    catAll: 'All',
    catRamen: 'Ramen',
    catChips: 'Chips',
    catCandy: 'Candy',
    catDrinks: 'Drinks',
    catBiscuits: 'Biscuits',

    addToCart: '+ Add to Cart',
    inCart: '✓ In Cart',
    outOfStock: 'Unavailable',
    badgeNew: 'New',
    badgeFeatured: '⭐ Featured',
    badgeOutOfStock: 'Out of Stock',

    catalogHeroBadge: '🇰🇷 Best Authentic Korean Products',
    catalogHeroTitle: 'Korean Snacks at Your Door',
    catalogHeroSubtitle: '+ authentic products delivered to your door',
    searchPlaceholder: 'Search products, brands...',
    filterBtn: '⚙️ Filters',
    noResultsTitle: 'No matching products',
    noResultsDesc: 'Try changing filters or different search keywords',
    productsLabel: 'products',
    pageLabel: 'Page',
    ofLabel: 'of',
    sortFeatured: 'Featured First',
    sortPriceAsc: 'Price: Low to High',
    sortPriceDesc: 'Price: High to Low',
    sortRating: 'Highest Rated',
    sortName: 'Name A–Z',
    maxPriceLabel: 'Max Price',
    minRatingLabel: 'Min Rating',
    inStockOnly: 'In Stock Only',
    resetFilters: '↺ Reset Filters',

    cartTitle: '🛒 Shopping Cart',
    emptyCartTitle: 'Cart is Empty',
    emptyCartMsg: "You haven't added any products yet. Browse our store and discover amazing Korean snacks!",
    browseStore: 'Browse Store 🇰🇷',
    clearCart: '🗑️ Clear Cart',
    subtotal: 'Subtotal',
    shippingFee: 'Shipping',
    freeShippingLabel: 'Free 🎉',
    totalLabel: 'Total',
    checkoutBtn: 'Checkout →',
    continueShoppingBtn: 'Continue Shopping',
    orderSummaryTitle: 'Order Summary',

    backToCartLink: '← Back to Cart',
    checkoutTitle: 'Checkout',
    personalInfoTitle: '👤 Personal Information',
    fullNameLabel: 'Full Name',
    namePlaceholder: 'e.g. John Smith',
    phoneLabel: 'Phone Number',
    phonePlaceholder: 'e.g. 0501234567',
    addressTitle: '📍 Delivery Address',
    cityLabel: 'City',
    cityPlaceholder: 'Riyadh',
    districtLabel: 'District',
    districtPlaceholder: 'Al-Nuzha District',
    streetLabel: 'Street Name',
    streetPlaceholder: 'King Fahd Road',
    buildingLabel: 'Building / Apartment',
    buildingPlaceholder: 'Building 12, Apt 3',
    notesLabel: 'Additional Notes',
    notesPlaceholder: 'Any special delivery instructions...',
    paymentTitle: '💳 Payment Method',
    pmCod: 'Cash on Delivery',
    pmCodDesc: 'Pay cash when your order arrives',
    pmCredit: 'Credit Card',
    pmCreditDesc: 'Visa, Mastercard, Mada',
    pmStc: 'STC Pay',
    pmStcDesc: 'Pay via STC Pay app',
    confirmOrderBtn: '📲 Send Order via WhatsApp',
    secureInfo: 'Your information is secure',
    shippingLabel: 'Shipping',
    freeLabel: 'Free',
    nameRequired: 'Name is required',
    phoneRequired: 'Phone number is required',
    phoneInvalid: 'Invalid phone number',
    cityRequired: 'City is required',
    streetRequired: 'Street name is required',
    formError: 'Please fix the errors in the form',
    orderSuccessTitle: 'Order Received!',
    orderTotalLabel: 'Order Total',
    shopAgainBtn: 'Shop Again 🛍️',

    storeLink: 'Store',
    productNotFound: 'Product Not Found',
    backToStoreBtn: 'Back to Store',
    quantityLabel: 'Qty',
    unavailableBtn: 'Currently Unavailable',
    viewCartBtn: 'View Cart',
    reviewsLabel: 'reviews',
    specsTitle: 'Product Specs',
    specWeight: 'Weight',
    specServings: 'Servings',
    specOrigin: 'Origin',
    specBrand: 'Brand',
    specCategory: 'Category',
    specHeat: 'Heat Level',
    specAvailability: 'Availability',
    specAvailable: '✅ In Stock',
    specOutOfStock: '❌ Out of Stock',
    viewAllLink: 'View All',
    outOfStockBadge: 'Out of Stock',
    heatLabels: ['', '🌶️ Mild', '🌶️🌶️ Medium', '🌶️🌶️🌶️ Hot', '🌶️🌶️🌶️🌶️ Very Hot', '🌶️🌶️🌶️🌶️🌶️ Fire!'],
    galleryViews: {
      رامن: ['Product', 'Serving', 'Ingredients', 'Packaging'],
      رقائق: ['Product', 'In Bowl', 'Seasoning', 'Packaging'],
      حلوى: ['Product', 'Presentation', 'Ingredients', 'Packaging'],
      مشروبات: ['Product', 'Cold', 'On Ice', 'Packaging'],
      بسكويت: ['Product', 'With Tea', 'Sliced', 'Packaging'],
    },

    footerTagline: 'The best authentic Korean snacks in Saudi Arabia',
    footerContactTitle: 'Contact Us',
    footerEmail: 'info@hanooksnacks.com',
    footerPhone: '+966 50 000 0000',
    footerAddress: 'Riyadh, Saudi Arabia',
    footerHours: 'Sun–Thu: 9 AM – 9 PM',
    footerLinksTitle: 'Quick Links',
    footerHome: 'Home',
    footerStore: 'Store',
    footerCart: 'Cart',
    footerRights: 'All Rights Reserved',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('hanook-lang') || 'ar');

  useEffect(() => {
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
    localStorage.setItem('hanook-lang', lang);
  }, [lang]);

  const t = (key) => T[lang][key] ?? T.ar[key] ?? key;
  const toggleLang = () => setLang(l => l === 'ar' ? 'en' : 'ar');
  const isRTL = lang === 'ar';

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLang, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
