import { useState, useEffect } from 'react';
import { LanguageContext } from './LanguageContext';

const T = {
  ar: {
    currency: '₪',
    storeName: 'Lulu Tokki',
    storeSubtitle: 'Korean Snacks Store',
    navStore: 'المتجر',
    navAdmin: 'الإدارة',
    langToggle: 'עברית',

    heroTitle: 'متجر الأمنيات — سناكات كورية وغير كورية ومفاجآت',
    heroSubtitle: 'اكتشف أشهى التشكيلات من السناكات الكورية — مشروبات، حلويات، ورقائق وغيرها',
    heroShopNow: 'تسوق الآن',
    heroBrowse: 'تصفح المتجر',
    heroStatProducts: 'منتج',
    heroStatCategories: 'فئات',
    heroStatAuthentic: 'أصيل',
    heroStatDelivery: 'توصيل سريع',
    feat1Title: 'شحن مجاني',
    feat1Desc: 'عند الطلب فوق 100 ₪',
    feat2Title: 'منتجات أصيلة',
    feat2Desc: 'مستوردة مباشرة من كوريا',
    feat3Title: 'توصيل سريع',
    feat3Desc: 'شحن سريع مضمون',
    feat4Title: 'دفع آمن',
    feat4Desc: 'الدفع عند الاستلام',
    mostBoughtTitle: 'الأكثر مبيعاً',
    mostBoughtSubtitle: 'المفضلة لدى عملائنا',
    viewAllProducts: 'تصفح جميع المنتجات',
    categoriesTitle: 'تصفح الفئات',
    catItems: 'منتج',

    catAll: 'الكل',
    catRamen: 'رامن',
    catChips: 'رقائق',
    catCandy: 'حلوى',
    catDrinks: 'مشروبات',
    catBiscuits: 'بسكويت',

    addToCart: '+ أضف للسلة',
    inCart: '✓ في السلة',
    outOfStock: 'غير متاح',
    badgeNew: 'جديد',
    badgeFeatured: '⭐ مميز',
    badgeOutOfStock: 'نفد المخزون',

    catalogHeroBadge: '🐰 أفضل المنتجات الكورية الأصيلة',
    catalogHeroTitle: 'وجبات كورية في بيتك',
    catalogHeroSubtitle: '+ منتج أصيل يصلك على باب البيت',
    searchPlaceholder: 'ابحث عن منتج، علامة تجارية...',
    filterBtn: '⚙️ فلاتر',
    noResultsTitle: 'لا توجد منتجات مطابقة',
    noResultsDesc: 'جرب تغيير الفلاتر أو البحث بكلمات مختلفة',
    productsLabel: 'منتج',
    pageLabel: 'صفحة',
    ofLabel: 'من',
    sortFeatured: 'المميزة أولاً',
    sortPriceAsc: 'السعر: الأقل أولاً',
    sortPriceDesc: 'السعر: الأعلى أولاً',
    sortRating: 'الأعلى تقييماً',
    sortName: 'الاسم أبجدياً',
    maxPriceLabel: 'الحد الأقصى للسعر',
    minRatingLabel: 'الحد الأدنى للتقييم',
    inStockOnly: 'المتاح فقط',
    resetFilters: '↺ إعادة ضبط الفلاتر',

    cartTitle: '🛒 سلة المشتريات',
    emptyCartTitle: 'السلة فارغة',
    emptyCartMsg: 'لم تضف أي منتجات بعد. تصفح متجرنا واكتشف أشهى الوجبات الكورية!',
    browseStore: 'تصفح المتجر 🐰',
    clearCart: '🗑️ إفراغ السلة',
    subtotal: 'المجموع الفرعي',
    shippingFee: 'رسوم الشحن',
    freeShippingLabel: 'مجاني 🎉',
    totalLabel: 'الإجمالي',
    checkoutBtn: 'إتمام الطلب ←',
    continueShoppingBtn: 'متابعة التسوق',
    orderSummaryTitle: 'ملخص الطلب',

    backToCartLink: '← العودة للسلة',
    checkoutTitle: 'إتمام الطلب',
    personalInfoTitle: '👤 المعلومات الشخصية',
    fullNameLabel: 'الاسم الكامل',
    namePlaceholder: 'مثال: أحمد محمد العمري',
    phoneLabel: 'رقم التلفون',
    phonePlaceholder: 'مثال: 0501234567',
    addressTitle: '📍 عنوان التوصيل',
    cityLabel: 'المدينة',
    cityPlaceholder: 'باقة الغربية',
    districtLabel: 'الحي',
    districtPlaceholder: 'حي النملات',
    streetLabel: 'اسم الشارع',
    streetPlaceholder: 'صلاح الدين',
    buildingLabel: 'رقم المبنى / الشقة',
    buildingPlaceholder: 'مبنى 12، شقة 3',
    notesLabel: 'ملاحظات إضافية',
    notesPlaceholder: 'أي تعليمات خاصة للتوصيل...',
    paymentTitle: '💳 طريقة الدفع',
    pmCod: 'الدفع عند الاستلام',
    pmCodDesc: 'ادفع نقداً عند وصول طلبك',
    pmCredit: 'بطاقة ائتمانية',
    pmCreditDesc: 'فيزا، ماستركارد، مدى',
    pmStc: 'STC Pay',
    pmStcDesc: 'الدفع عبر تطبيق STC Pay',
    confirmOrderBtn: '📲 أرسل الطلب عبر واتساب',
    secureInfo: 'معلوماتك محمية وآمنة',
    shippingLabel: 'الشحن',
    freeLabel: 'مجاني',
    nameRequired: 'الاسم مطلوب',
    phoneRequired: 'رقم التلفون مطلوب',
    phoneInvalid: 'رقم التلفون غير صحيح',
    cityRequired: 'المدينة مطلوبة',
    streetRequired: 'اسم الشارع مطلوب',
    formError: 'يرجى تصحيح الأخطاء في النموذج',
    orderSuccessTitle: 'تم استلام طلبك!',
    orderTotalLabel: 'إجمالي الطلب',
    shopAgainBtn: 'تسوق مجدداً 🛍️',

    storeLink: 'المتجر',
    productNotFound: 'المنتج غير موجود',
    backToStoreBtn: 'العودة للمتجر',
    quantityLabel: 'الكمية',
    unavailableBtn: 'غير متاح حالياً',
    viewCartBtn: 'عرض السلة',
    reviewsLabel: 'تقييم',
    specsTitle: 'مواصفات المنتج',
    specWeight: 'الوزن',
    specServings: 'الحصص',
    specOrigin: 'البلد',
    specBrand: 'العلامة التجارية',
    specCategory: 'الفئة',
    specHeat: 'مستوى الحرارة',
    specAvailability: 'التوفر',
    specAvailable: '✅ متاح',
    specOutOfStock: '❌ نفد المخزون',
    viewAllLink: 'عرض الكل',
    outOfStockBadge: 'نفد المخزون',
    heatLabels: ['', '🌶️ خفيف', '🌶️🌶️ معتدل', '🌶️🌶️🌶️ حار', '🌶️🌶️🌶️🌶️ حار جداً', '🌶️🌶️🌶️🌶️🌶️ ناري!'],
    galleryViews: {
      رامن: ['المنتج', 'طريقة التقديم', 'المكونات', 'العبوة'],
      رقائق: ['المنتج', 'في الوعاء', 'التوابل', 'العبوة'],
      حلوى: ['المنتج', 'التقديم', 'المكونات', 'العبوة'],
      مشروبات: ['المنتج', 'بارد', 'مع الثلج', 'العبوة'],
      بسكويت: ['المنتج', 'مع الشاي', 'مقطّع', 'العبوة'],
    },

    footerTagline: 'أفضل الوجبات الكورية الأصيلة في باقة الغربية',
    footerContactTitle: 'تواصل معنا',
    footerEmail: 'noorabutamam304@gmail.com',
    footerPhone: '+972547639465',
    footerAddress: 'باقة الغربية',
    footerHours: 'الأحد – الخميس: 9 ص – 9 م',
    footerLinksTitle: 'روابط سريعة',
    footerHome: 'الرئيسية',
    footerStore: 'المتجر',
    footerCart: 'السلة',
    footerRights: 'جميع الحقوق محفوظة',

    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    signOut: 'تسجيل الخروج',
    myAccount: 'حسابي',
    emailLabel: 'البريد الإلكتروني',
    emailPlaceholder: 'example@email.com',
    emailRequired: 'البريد الإلكتروني مطلوب',
    passwordLabel: 'كلمة المرور',
    confirmPasswordLabel: 'تأكيد كلمة المرور',
    loginBtn: 'دخول',
    signupBtn: 'إنشاء حساب',
    noAccount: 'ليس لديك حساب؟',
    hasAccount: 'لديك حساب بالفعل؟',
    emailExistsError: 'البريد الإلكتروني مستخدم بالفعل',
    invalidCredentialsError: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    passwordMismatch: 'كلمة المرور غير متطابقة',
    passwordTooShort: 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    orderHistoryTab: 'سجل الطلبات',
    wishlistTab: 'المفضلة',
    emptyHistoryMsg: 'لا توجد طلبات سابقة',
    emptyWishlistMsg: 'لم تضف أي منتجات للمفضلة بعد',
    loginToWishlistMsg: 'سجل دخولك لإضافة المنتجات للمفضلة',
    orderDateLabel: 'تاريخ الطلب',
    orderSentWhatsapp: 'تم الإرسال عبر واتساب',
    addToWishlist: 'أضف للمفضلة',
    removeFromWishlist: 'إزالة من المفضلة',

    promoCodeLabel: 'كود الخصم',
    promoPlaceholder: 'أدخل الكود...',
    applyPromoBtn: 'تطبيق',
    promoInvalid: 'الكود غير صحيح أو منتهي الصلاحية',
    discountLabel: 'خصم',
    removePromoBtn: 'إزالة',
  },

  he: {
    currency: '₪',
    storeName: 'Lulu Tokki',
    storeSubtitle: 'Korean Snacks Store',
    navStore: 'החנות',
    navAdmin: 'ניהול',
    langToggle: 'EN',

    heroTitle: 'חנות המשאלות — חטיפים קוריאניים ולא רק, והפתעות',
    heroSubtitle: 'גלו את מיטב מבחר החטיפים הקוריאניים — משקאות, ממתקים, צ׳יפס ועוד',
    heroShopNow: 'קנו עכשיו',
    heroBrowse: 'עיון בחנות',
    heroStatProducts: 'מוצרים',
    heroStatCategories: 'קטגוריות',
    heroStatAuthentic: 'אותנטי',
    heroStatDelivery: 'משלוח מהיר',
    feat1Title: 'משלוח חינם',
    feat1Desc: 'בהזמנות מעל ₪100',
    feat2Title: 'מוצרים אותנטיים',
    feat2Desc: 'מיובאים ישירות מקוריאה',
    feat3Title: 'משלוח מהיר',
    feat3Desc: 'משלוח מהיר ומובטח',
    feat4Title: 'תשלום מאובטח',
    feat4Desc: 'תשלום במזומן בעת המסירה',
    mostBoughtTitle: 'הנמכרים ביותר',
    mostBoughtSubtitle: 'המועדפים על לקוחותינו',
    viewAllProducts: 'עיון בכל המוצרים',
    categoriesTitle: 'עיון בקטגוריות',
    catItems: 'מוצרים',

    catAll: 'הכל',
    catRamen: 'ראמן',
    catChips: 'צ׳יפס',
    catCandy: 'ממתקים',
    catDrinks: 'משקאות',
    catBiscuits: 'ביסקוויטים',

    addToCart: '+ הוספה לעגלה',
    inCart: '✓ בעגלה',
    outOfStock: 'לא זמין',
    badgeNew: 'חדש',
    badgeFeatured: '⭐ מומלץ',
    badgeOutOfStock: 'אזל מהמלאי',

    catalogHeroBadge: '🐰 מיטב המוצרים הקוריאניים האותנטיים',
    catalogHeroTitle: 'חטיפים קוריאניים עד הבית',
    catalogHeroSubtitle: '+ מוצרים אותנטיים שמגיעים עד דלת ביתכם',
    searchPlaceholder: 'חיפוש מוצר, מותג...',
    filterBtn: '⚙️ סינון',
    noResultsTitle: 'לא נמצאו מוצרים תואמים',
    noResultsDesc: 'נסו לשנות את הסינון או לחפש במילים אחרות',
    productsLabel: 'מוצרים',
    pageLabel: 'עמוד',
    ofLabel: 'מתוך',
    sortFeatured: 'מומלצים תחילה',
    sortPriceAsc: 'מחיר: מהנמוך לגבוה',
    sortPriceDesc: 'מחיר: מהגבוה לנמוך',
    sortRating: 'הדירוג הגבוה ביותר',
    sortName: 'שם א׳–ת׳',
    maxPriceLabel: 'מחיר מקסימלי',
    minRatingLabel: 'דירוג מינימלי',
    inStockOnly: 'במלאי בלבד',
    resetFilters: '↺ איפוס סינון',

    cartTitle: '🛒 עגלת הקניות',
    emptyCartTitle: 'העגלה ריקה',
    emptyCartMsg: 'עדיין לא הוספתם מוצרים. עיינו בחנות שלנו וגלו חטיפים קוריאניים מדהימים!',
    browseStore: 'עיון בחנות 🐰',
    clearCart: '🗑️ ריקון העגלה',
    subtotal: 'סכום ביניים',
    shippingFee: 'דמי משלוח',
    freeShippingLabel: 'חינם 🎉',
    totalLabel: 'סה״כ',
    checkoutBtn: 'מעבר לתשלום ←',
    continueShoppingBtn: 'המשך בקניות',
    orderSummaryTitle: 'סיכום הזמנה',

    backToCartLink: '← חזרה לעגלה',
    checkoutTitle: 'תשלום',
    personalInfoTitle: '👤 פרטים אישיים',
    fullNameLabel: 'שם מלא',
    namePlaceholder: 'לדוגמה: ישראל ישראלי',
    phoneLabel: 'מספר טלפון',
    phonePlaceholder: 'לדוגמה: 0501234567',
    addressTitle: '📍 כתובת למשלוח',
    cityLabel: 'עיר',
    cityPlaceholder: 'באקה אל-ע׳רביה',
    districtLabel: 'שכונה',
    districtPlaceholder: 'שכונת אל-נמלאת',
    streetLabel: 'שם הרחוב',
    streetPlaceholder: 'סלאח א-דין',
    buildingLabel: 'מספר בניין / דירה',
    buildingPlaceholder: 'בניין 12, דירה 3',
    notesLabel: 'הערות נוספות',
    notesPlaceholder: 'הוראות מיוחדות למשלוח...',
    paymentTitle: '💳 אמצעי תשלום',
    pmCod: 'תשלום במזומן בעת המסירה',
    pmCodDesc: 'שלמו במזומן כאשר ההזמנה מגיעה',
    pmCredit: 'כרטיס אשראי',
    pmCreditDesc: 'ויזה, מאסטרקארד, מאדא',
    pmStc: 'STC Pay',
    pmStcDesc: 'תשלום דרך אפליקציית STC Pay',
    confirmOrderBtn: '📲 שליחת ההזמנה בוואטסאפ',
    secureInfo: 'המידע שלכם מאובטח ומוגן',
    shippingLabel: 'משלוח',
    freeLabel: 'חינם',
    nameRequired: 'נדרש שם',
    phoneRequired: 'נדרש מספר טלפון',
    phoneInvalid: 'מספר טלפון לא תקין',
    cityRequired: 'נדרשת עיר',
    streetRequired: 'נדרש שם רחוב',
    formError: 'אנא תקנו את השגיאות בטופס',
    orderSuccessTitle: 'ההזמנה התקבלה!',
    orderTotalLabel: 'סך ההזמנה',
    shopAgainBtn: 'לקניות נוספות 🛍️',

    storeLink: 'החנות',
    productNotFound: 'המוצר לא נמצא',
    backToStoreBtn: 'חזרה לחנות',
    quantityLabel: 'כמות',
    unavailableBtn: 'לא זמין כעת',
    viewCartBtn: 'הצגת העגלה',
    reviewsLabel: 'ביקורות',
    specsTitle: 'מפרט המוצר',
    specWeight: 'משקל',
    specServings: 'מנות',
    specOrigin: 'ארץ ייצור',
    specBrand: 'מותג',
    specCategory: 'קטגוריה',
    specHeat: 'רמת חריפות',
    specAvailability: 'זמינות',
    specAvailable: '✅ במלאי',
    specOutOfStock: '❌ אזל מהמלאי',
    viewAllLink: 'הצגת הכל',
    outOfStockBadge: 'אזל מהמלאי',
    heatLabels: ['', '🌶️ עדין', '🌶️🌶️ בינוני', '🌶️🌶️🌶️ חריף', '🌶️🌶️🌶️🌶️ חריף מאוד', '🌶️🌶️🌶️🌶️🌶️ לוהט!'],
    galleryViews: {
      رامن: ['מוצר', 'הגשה', 'מרכיבים', 'אריזה'],
      رقائق: ['מוצר', 'בקערה', 'תיבול', 'אריזה'],
      حلوى: ['מוצר', 'הגשה', 'מרכיבים', 'אריזה'],
      مشروبات: ['מוצר', 'קר', 'עם קרח', 'אריזה'],
      بسكويت: ['מוצר', 'עם תה', 'פרוס', 'אריזה'],
    },

    footerTagline: 'מיטב החטיפים הקוריאניים האותנטיים בבאקה אל-ע׳רביה',
    footerContactTitle: 'צרו קשר',
    footerEmail: 'noorabutamam304@gmail.com',
    footerPhone: '+972547639465',
    footerAddress: 'באקה אל-ע׳רביה',
    footerHours: 'ראשון – חמישי: 9:00 – 21:00',
    footerLinksTitle: 'קישורים מהירים',
    footerHome: 'בית',
    footerStore: 'החנות',
    footerCart: 'עגלה',
    footerRights: 'כל הזכויות שמורות',

    signIn: 'התחברות',
    signUp: 'הרשמה',
    signOut: 'התנתקות',
    myAccount: 'החשבון שלי',
    emailLabel: 'כתובת אימייל',
    emailPlaceholder: 'example@email.com',
    emailRequired: 'נדרש אימייל',
    passwordLabel: 'סיסמה',
    confirmPasswordLabel: 'אימות סיסמה',
    loginBtn: 'התחברות',
    signupBtn: 'יצירת חשבון',
    noAccount: 'אין לכם חשבון?',
    hasAccount: 'כבר יש לכם חשבון?',
    emailExistsError: 'האימייל כבר רשום במערכת',
    invalidCredentialsError: 'אימייל או סיסמה שגויים',
    passwordMismatch: 'הסיסמאות אינן תואמות',
    passwordTooShort: 'הסיסמה חייבת להכיל לפחות 6 תווים',
    orderHistoryTab: 'היסטוריית הזמנות',
    wishlistTab: 'מועדפים',
    emptyHistoryMsg: 'אין הזמנות קודמות',
    emptyWishlistMsg: 'עדיין לא הוספתם מוצרים למועדפים',
    loginToWishlistMsg: 'התחברו כדי להוסיף מוצרים למועדפים',
    orderDateLabel: 'תאריך הזמנה',
    orderSentWhatsapp: 'נשלח בוואטסאפ',
    addToWishlist: 'הוספה למועדפים',
    removeFromWishlist: 'הסרה מהמועדפים',

    promoCodeLabel: 'קוד הנחה',
    promoPlaceholder: 'הזינו קוד...',
    applyPromoBtn: 'החלה',
    promoInvalid: 'קוד שגוי או שפג תוקפו',
    discountLabel: 'הנחה',
    removePromoBtn: 'הסרה',
  },

  en: {
    currency: '₪',
    storeName: 'Lulu Tokki',
    storeSubtitle: 'Korean Snacks Store',
    navStore: 'Store',
    navAdmin: 'Admin',
    langToggle: 'عربي',

    heroTitle: 'Wishes Store — Korean Snacks & More, Plus Surprises',
    heroSubtitle: 'Discover the best selection of Korean snacks — drinks, sweets, chips and more',
    heroShopNow: 'Shop Now',
    heroBrowse: 'Browse Store',
    heroStatProducts: 'Products',
    heroStatCategories: 'Categories',
    heroStatAuthentic: 'Authentic',
    heroStatDelivery: 'Fast Delivery',
    feat1Title: 'Free Shipping',
    feat1Desc: 'On orders above ₪100',
    feat2Title: 'Authentic Products',
    feat2Desc: 'Imported directly from Korea',
    feat3Title: 'Fast Delivery',
    feat3Desc: 'Fast shipping guaranteed',
    feat4Title: 'Secure Payment',
    feat4Desc: 'Cash on delivery',
    mostBoughtTitle: 'Best Sellers',
    mostBoughtSubtitle: 'Customer Favorites',
    viewAllProducts: 'Browse All Products',
    categoriesTitle: 'Browse Categories',
    catItems: 'items',

    catAll: 'All',
    catRamen: 'Ramen',
    catChips: 'Chips',
    catCandy: 'Candy',
    catDrinks: 'Drinks',
    catBiscuits: 'Biscuits',

    addToCart: '+ Add to Cart',
    inCart: '✓ In Cart',
    outOfStock: 'Unavailable',
    badgeNew: 'New',
    badgeFeatured: '⭐ Featured',
    badgeOutOfStock: 'Out of Stock',

    catalogHeroBadge: '🐰 Best Authentic Korean Products',
    catalogHeroTitle: 'Korean Snacks at Your Door',
    catalogHeroSubtitle: '+ authentic products delivered to your door',
    searchPlaceholder: 'Search products, brands...',
    filterBtn: '⚙️ Filters',
    noResultsTitle: 'No matching products',
    noResultsDesc: 'Try changing filters or different search keywords',
    productsLabel: 'products',
    pageLabel: 'Page',
    ofLabel: 'of',
    sortFeatured: 'Featured First',
    sortPriceAsc: 'Price: Low to High',
    sortPriceDesc: 'Price: High to Low',
    sortRating: 'Highest Rated',
    sortName: 'Name A–Z',
    maxPriceLabel: 'Max Price',
    minRatingLabel: 'Min Rating',
    inStockOnly: 'In Stock Only',
    resetFilters: '↺ Reset Filters',

    cartTitle: '🛒 Shopping Cart',
    emptyCartTitle: 'Cart is Empty',
    emptyCartMsg: "You haven't added any products yet. Browse our store and discover amazing Korean snacks!",
    browseStore: 'Browse Store 🐰',
    clearCart: '🗑️ Clear Cart',
    subtotal: 'Subtotal',
    shippingFee: 'Shipping',
    freeShippingLabel: 'Free 🎉',
    totalLabel: 'Total',
    checkoutBtn: 'Checkout →',
    continueShoppingBtn: 'Continue Shopping',
    orderSummaryTitle: 'Order Summary',

    backToCartLink: '← Back to Cart',
    checkoutTitle: 'Checkout',
    personalInfoTitle: '👤 Personal Information',
    fullNameLabel: 'Full Name',
    namePlaceholder: 'e.g. John Smith',
    phoneLabel: 'Phone Number',
    phonePlaceholder: 'e.g. 0501234567',
    addressTitle: '📍 Delivery Address',
    cityLabel: 'City',
    cityPlaceholder: 'Baqa al-Gharbiyye',
    districtLabel: 'District',
    districtPlaceholder: 'Al-Namlat',
    streetLabel: 'Street Name',
    streetPlaceholder: 'Salah al-Din',
    buildingLabel: 'Building / Apartment',
    buildingPlaceholder: 'Building 12, Apt 3',
    notesLabel: 'Additional Notes',
    notesPlaceholder: 'Any special delivery instructions...',
    paymentTitle: '💳 Payment Method',
    pmCod: 'Cash on Delivery',
    pmCodDesc: 'Pay cash when your order arrives',
    pmCredit: 'Credit Card',
    pmCreditDesc: 'Visa, Mastercard, Mada',
    pmStc: 'STC Pay',
    pmStcDesc: 'Pay via STC Pay app',
    confirmOrderBtn: '📲 Send Order via WhatsApp',
    secureInfo: 'Your information is secure',
    shippingLabel: 'Shipping',
    freeLabel: 'Free',
    nameRequired: 'Name is required',
    phoneRequired: 'Phone number is required',
    phoneInvalid: 'Invalid phone number',
    cityRequired: 'City is required',
    streetRequired: 'Street name is required',
    formError: 'Please fix the errors in the form',
    orderSuccessTitle: 'Order Received!',
    orderTotalLabel: 'Order Total',
    shopAgainBtn: 'Shop Again 🛍️',

    storeLink: 'Store',
    productNotFound: 'Product Not Found',
    backToStoreBtn: 'Back to Store',
    quantityLabel: 'Qty',
    unavailableBtn: 'Currently Unavailable',
    viewCartBtn: 'View Cart',
    reviewsLabel: 'reviews',
    specsTitle: 'Product Specs',
    specWeight: 'Weight',
    specServings: 'Servings',
    specOrigin: 'Origin',
    specBrand: 'Brand',
    specCategory: 'Category',
    specHeat: 'Heat Level',
    specAvailability: 'Availability',
    specAvailable: '✅ In Stock',
    specOutOfStock: '❌ Out of Stock',
    viewAllLink: 'View All',
    outOfStockBadge: 'Out of Stock',
    heatLabels: ['', '🌶️ Mild', '🌶️🌶️ Medium', '🌶️🌶️🌶️ Hot', '🌶️🌶️🌶️🌶️ Very Hot', '🌶️🌶️🌶️🌶️🌶️ Fire!'],
    galleryViews: {
      رامن: ['Product', 'Serving', 'Ingredients', 'Packaging'],
      رقائق: ['Product', 'In Bowl', 'Seasoning', 'Packaging'],
      حلوى: ['Product', 'Presentation', 'Ingredients', 'Packaging'],
      مشروبات: ['Product', 'Cold', 'On Ice', 'Packaging'],
      بسكويت: ['Product', 'With Tea', 'Sliced', 'Packaging'],
    },

    footerTagline: 'The best authentic Korean snacks in Baqa al-Gharbiyye',
    footerContactTitle: 'Contact Us',
    footerEmail: 'noorabutamam304@gmail.com',
    footerPhone: '+972547639465',
    footerAddress: 'Baqa al-Gharbiyye',
    footerHours: 'Sun–Thu: 9 AM – 9 PM',
    footerLinksTitle: 'Quick Links',
    footerHome: 'Home',
    footerStore: 'Store',
    footerCart: 'Cart',
    footerRights: 'All Rights Reserved',

    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    myAccount: 'My Account',
    emailLabel: 'Email Address',
    emailPlaceholder: 'example@email.com',
    emailRequired: 'Email is required',
    passwordLabel: 'Password',
    confirmPasswordLabel: 'Confirm Password',
    loginBtn: 'Sign In',
    signupBtn: 'Create Account',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    emailExistsError: 'Email is already registered',
    invalidCredentialsError: 'Incorrect email or password',
    passwordMismatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
    orderHistoryTab: 'Order History',
    wishlistTab: 'Wishlist',
    emptyHistoryMsg: 'No previous orders',
    emptyWishlistMsg: "You haven't added any products to your wishlist yet",
    loginToWishlistMsg: 'Sign in to add products to your wishlist',
    orderDateLabel: 'Order Date',
    orderSentWhatsapp: 'Sent via WhatsApp',
    addToWishlist: 'Add to Wishlist',
    removeFromWishlist: 'Remove from Wishlist',

    promoCodeLabel: 'Promo Code',
    promoPlaceholder: 'Enter code...',
    applyPromoBtn: 'Apply',
    promoInvalid: 'Invalid or expired code',
    discountLabel: 'Discount',
    removePromoBtn: 'Remove',
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('hanook-lang') || 'ar');

  useEffect(() => {
    document.documentElement.dir = lang === 'en' ? 'ltr' : 'rtl';
    document.documentElement.lang = lang;
    localStorage.setItem('hanook-lang', lang);
  }, [lang]);

  const t = (key) => T[lang]?.[key] ?? T.ar[key] ?? key;
  // Cycle through the three supported languages: Arabic → Hebrew → English.
  const toggleLang = () => setLang(l => (l === 'ar' ? 'he' : l === 'he' ? 'en' : 'ar'));
  const isRTL = lang !== 'en';
  // Picks a value by the active language: tr(arabic, english, hebrew).
  const tr = (ar, en, he) => (lang === 'en' ? en : lang === 'he' ? he : ar);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, toggleLang, isRTL, tr }}>
      {children}
    </LanguageContext.Provider>
  );
}
